#! /usr/bin/env python3
# -*- coding: utf-8 -*-

'''
      Copyright 2016,王思远 <darknightghost.cn@gmail.com>
      This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
      You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
'''

import os
import sys
import compressor

compress_format = None
input_dir = None
extract_dir = None
install_script = None
output = None

def main(argv):
    #Translate arguments
    if len(argv) < 11:
        usage()
        return 64

    trans_state, help_flag = translate_args(argv)
    if not trans_state:
        usage()
        return 64

    elif help_flag:
        usage()
        return 0


    #Load compressor
    return 0

def translate_args(argv):
    return True, True

def usage():
    print("Usage:")
    print(' ' * 4 \
            + "%s [compressor-options] -f format -d input-dir -e extract-dir [-i install-script] -o output"\
            %(__file__))

    #Get options
    options = [
        [
            "Options:",[
                ("-d input-dir", "Input directory."),
                ("-e extract_dir", "Extract directory."),
                ("-i install-script", "Script to run after extract."),
                ("-o output", "Output file."),
                ("-f format", "Compress format."),
                ("--help", "Show this help.")
            ]
        ]
    ]

    #Print options
    for o in options:
        print("")
        print(o[0])
        for l in o[1]:
            print(' ' * 4 + "%-40s%s"%(l[0], l[1]))

    print("")


ret = main(sys.argv)
exit(ret)
