#! /usr/bin/env python3
# -*- coding: utf-8 -*-

'''
      Copyright 2016,王思远 <darknightghost.cn@gmail.com>
      This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
      You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
'''

import os
import sys
import compressors

arg_dict = {}

def main(argv):
    #Translate arguments
    if len(argv) < 2:
        usage()
        return 64

    compressor, help_flag = translate_args(argv)

    if help_flag:
        usage()
        return 0

    elif compressor == None:
        usage()
        return 64

    ret = Compressor.mksfx()

    return ret

def translate_args(argv):
    global arg_dict

    #Get args
    key = None
    for i in range(1, len(argv)):
        if argv[i][0] == "-":
            if key == None:
                key = argv[i]

            else:
                arg_dict[key] = None
                key = argv[i]

        else:
            if key == None:
                return None, False

            else:
                arg_dict[key] = argv[i]
                key = None

    if key != None:
        arg_dict[key] = None

    if "--help" in arg_dict.keys():
        return None, True

    #Load compressor
    try:
        compressor = compressors.get_compressor(arg_dict["-f"])
        comp = compressor(
                arg_dict["-d"],
                arg_dict["-e"],
                arg_dict["-i"],
                arg_dict["-o"])

        if not comp.translate_args(arg_dict):
            return None, False

        return comp, False

    except KeyError:
        return None, False

def usage():
    print("Usage:")
    print(' ' * 4 \
            + "%s [compressor-options] -f format -d input-dir -e extract-dir [-i install-script] -o output"\
            %(__file__))

    compressor_list = compressors.get_compressor_list()
    print("Supported compressors:")
    for c in compressor_list:
        print(' ' * 4 + c)

    #Get options
    options = [
        [
            "Options:", [
                ("-d input-dir", "Input directory."),
                ("-e extract_dir", "Extract directory."),
                ("-i install-script", "Script to run after extract."),
                ("-o output", "Output file."),
                ("-f format", "Compress format."),
                ("--help", "Show this help.")
            ]
        ]
    ]

    for c in compressor_list:
        comp = compressors.get_compressor(c)
        o = ["Compressor %s options:"%(c),
                comp.get_options()]
        options.append(o)

    #Print options
    for o in options:
        print("")
        print(o[0])
        for l in o[1]:
            print(' ' * 4 + "%-40s%s"%(l[0], l[1]))

    print("")


ret = main(sys.argv)
exit(ret)
